---
# tasks file for role_tomcat
- name: add tomcat group
  group:
    name: tomcat

- name: add tomcat user
  user:
    name: tomcat
    group: tomcat
    home: /user/share/tomcat
    createhome: no

- name: create /opt/tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    mode: 0755

- name: download & unarchive
  unarchive:
    src: http://us.mirrors.quenda.co/apache/tomcat/tomcat-9/v9.0.31/bin/apache-tomcat-9.0.31.tar.gz
    dest: /opt/tomcat
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: create file service tomcat
  file:
   path: /etc/systemd/system/tomcat.service
   state: touch

- name: Config du fichier tomcat.service
  lineinfile:
   path: /etc/systemd/system/tomcat.service
   line: "{{ item }}"
  loop: "{{ list }}"


- name: Change ownership
  file:
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory

- name: Gestion du service
  systemd:
   daemon_reload: yes

- name: Start and enable Tomcat service
  systemd:
    name: tomcat
    state: started
    enabled: true
    daemon_reload: true




